# Generated by Django 6.1.1 on 2026-09-24 18:07

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_randomize_existing_product_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='donation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=store.models.generate_order_id, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='', editable=False, max_length=24, unique=True),
        ),
    ]
